# .github/workflows/ci.yaml

name: python-hello-world

on: [push, pull_request]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        python-version: [3.11, 3.12]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies with Poetry
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run tests
        run: |
          poetry run pytest --maxfail=1 --disable-warnings
